### ISSUE TITLE
Bug in connection

### ISSUE THREAD

**Issue by giladbeeri** [node-xmpp/node-xmpp-core#63] opened 2015-03-12 22:03 UTC
Today I found out a bug in the code. Even though nothing has changed, it started breaking.

After a lot of debugging, I found out that something has changed:
My package depends on `node-xmpp-client` version `1.0.0-alpha15`. This version depends on `node-xmpp-core` version `1.0.0-alpha10`. I found out that originally it downloaded the correct version, but if I run `npm install` now, it downloads *`node-xmpp-core 1.0.0-alpha14`*, even though it still points to `1.0.0-alpha10`.

This is caused because `node-xmpp-client` uses `~` when declaring the dependency of `node-xmpp-core`.

If so, it showed a bug in the new version (alpha14). For some reason,
after creating an XMPP client, and receiving a successful `online` event, a moment after (less than a second) an `error` event is emitted on the client with
`Error: read ECONNRESET`.

The XMPP server doesn't show any sign to an error or a warning, and as I said, running the same code with `alpha10` works, but with `alpha14` it always emits this error just after `online`.

**Comment by sonnyp** [comment] 2015-03-16 14:00
@giladbeeri can you tell me where that error occurs?

**Comment by giladbeeri** [comment] 2015-03-16 18:38
Here it is - generated with `new Error().stack` in the first line of the `error` event listener (removed the first line which comes from my file):

```
    at Client.emit (events.js:95:17)
    at Client.<anonymous> (/Users/gilad/Projects/btoc/web-services/xmpp-bridge/node_modules/node-xmpp-client/index.js:190:33)
    at Connection.emit (events.js:117:20)
    at CleartextStream.onDisconnect (/Users/gilad/Projects/btoc/web-services/xmpp-bridge/node_modules/node-xmpp-client/node_modules/node-xmpp-core/node_modules/reconnect-core/index.js:59:17)
    at CleartextStream.emit (events.js:117:20)
    at Socket.onerror (/Users/gilad/Projects/btoc/web-services/xmpp-bridge/node_modules/node-xmpp-client/node_modules/node-xmpp-core/node_modules/tls-connect/starttls.js:396:17)
    at Socket.emit (events.js:117:20)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
```

**Comment by sonnyp** [comment] 2015-10-20 17:19
@giladbeeri could you please update node-xmpp-client to the latest version and let me know if you still experience the issue.

**Comment by giladbeeri** [comment] 2015-10-20 17:32
The project isn't active anymore. Give me some time to check if I can set up the environment again and test.

**Comment by sonnyp** [comment] 2015-10-20 17:34
@giladbeeri that would be great, the issue is very likely to be fixed tough. Closing for now, please reopen if you can reproduce.

**Closed by sonnyp** 2015-10-20 17:34 UTC
